apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: graphrag-keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: graphrag-keycloak-postgres-rw
    database: keycloak
    usernameSecret:
      name: graphrag-keycloak-postgres-app
      key: username
    passwordSecret:
      name: graphrag-keycloak-postgres-app
      key: password
  ingress:
    enabled: true
    className: nginx
  http:
    httpEnabled: true
  hostname:
    hostname: https://127.0.0.1.nip.io/auth
    strict: true
    backchannelDynamic: true
  proxy:
    headers: xforwarded
  additionalOptions:
    - name: http-relative-path
      value: /auth
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 2Gi
