apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphrag-chatbot.fullname" . }}
  namespace: {{ include "graphrag-chatbot.namespace" . }}
  labels:
    {{- include "graphrag-chatbot.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.configuration.properties -}}
    {{- range $key, $value := .Values.configuration.properties -}}
      {{- if ne $value nil -}}
        {{- printf "%s: %s" $key ($value | quote) | nindent 2 -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
