apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: graphrag-realm-example
  namespace: keycloak
spec:
  keycloakCRName: graphrag-keycloak
  realm:
    id: graphrag
    realm: graphrag
    enabled: true
    registrationAllowed: false
    resetPasswordAllowed: false
    loginWithEmailAllowed: true
    duplicateEmailsAllowed: false
    users:
      - username: alice
        enabled: true
        emailVerified: true
        firstName: Alice
        lastName: Anderson
        email: alice@example.com
        credentials:
          - type: password
            value: alice123
            temporary: false
      - username: bob
        enabled: true
        emailVerified: true
        firstName: Bob
        lastName: Brown
        email: bob@example.com
        credentials:
          - type: password
            value: bob123
            temporary: false
    clients:
      - clientId: chatbot-app-client
        secret: null
        enabled: true
        protocol: openid-connect
        publicClient: true
        redirectUris:
          - https://127.0.0.1.nip.io/graphrag/
        webOrigins:
          - https://127.0.0.1.nip.io
        standardFlowEnabled: true
        directAccessGrantsEnabled: true
      - clientId: conversation-api-client
        secret: change-me-please
        enabled: true
        protocol: openid-connect
        publicClient: false
        redirectUris: []
        webOrigins: []
        standardFlowEnabled: true
        directAccessGrantsEnabled: true
