#
# Sample PostgreSQL cluster for Keycloak.
# See https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/
#
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres
spec:
  instances: 3
  storage:
    size: 1Gi
  superuserSecret:
    name: postgres-superuser
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-postgres-user
